/********************************************************************
* src/TEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEventDict();
extern void G__cpp_setup_inheritanceTEventDict();
extern void G__cpp_setup_typetableTEventDict();
extern void G__cpp_setup_memvarTEventDict();
extern void G__cpp_setup_globalTEventDict();
extern void G__cpp_setup_memfuncTEventDict();
extern void G__cpp_setup_funcTEventDict();
extern void G__set_cpp_environmentTEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEventDictLN_TClass;
extern G__linked_taginfo G__TEventDictLN_TBuffer;
extern G__linked_taginfo G__TEventDictLN_TMemberInspector;
extern G__linked_taginfo G__TEventDictLN_TObject;
extern G__linked_taginfo G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEventDictLN_TTrackerHit;
extern G__linked_taginfo G__TEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TEventDictLN_TEvent;
extern G__linked_taginfo G__TEventDictLN_vectorlETTrackerHitcOallocatorlETTrackerHitgRsPgR;
extern G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlETTrackerHitcOallocatorlETTrackerHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
