/********************************************************************
* src/TGlobalDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TGlobalDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGlobalDataDict();
extern void G__cpp_setup_inheritanceTGlobalDataDict();
extern void G__cpp_setup_typetableTGlobalDataDict();
extern void G__cpp_setup_memvarTGlobalDataDict();
extern void G__cpp_setup_globalTGlobalDataDict();
extern void G__cpp_setup_memfuncTGlobalDataDict();
extern void G__cpp_setup_funcTGlobalDataDict();
extern void G__set_cpp_environmentTGlobalDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TGlobalData.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGlobalDataDictLN_TClass;
extern G__linked_taginfo G__TGlobalDataDictLN_TBuffer;
extern G__linked_taginfo G__TGlobalDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TGlobalDataDictLN_TObject;
extern G__linked_taginfo G__TGlobalDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGlobalDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGlobalDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGlobalDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGlobalDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGlobalDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGlobalDataDictLN_TGlobalData;
extern G__linked_taginfo G__TGlobalDataDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR;
extern G__linked_taginfo G__TGlobalDataDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGlobalDataDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
