/********************************************************************
* src/TPulseIslandDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TPulseIslandDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPulseIslandDict();
extern void G__cpp_setup_inheritanceTPulseIslandDict();
extern void G__cpp_setup_typetableTPulseIslandDict();
extern void G__cpp_setup_memvarTPulseIslandDict();
extern void G__cpp_setup_globalTPulseIslandDict();
extern void G__cpp_setup_memfuncTPulseIslandDict();
extern void G__cpp_setup_funcTPulseIslandDict();
extern void G__set_cpp_environmentTPulseIslandDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TPulseIsland.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPulseIslandDictLN_TClass;
extern G__linked_taginfo G__TPulseIslandDictLN_TBuffer;
extern G__linked_taginfo G__TPulseIslandDictLN_TMemberInspector;
extern G__linked_taginfo G__TPulseIslandDictLN_TObject;
extern G__linked_taginfo G__TPulseIslandDictLN_string;
extern G__linked_taginfo G__TPulseIslandDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPulseIslandDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPulseIslandDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPulseIslandDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPulseIslandDictLN_TPulseIsland;
extern G__linked_taginfo G__TPulseIslandDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TPulseIslandDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
