/********************************************************************
* src/TTrackerHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TTrackerHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTrackerHitDict();
extern void G__cpp_setup_inheritanceTTrackerHitDict();
extern void G__cpp_setup_typetableTTrackerHitDict();
extern void G__cpp_setup_memvarTTrackerHitDict();
extern void G__cpp_setup_globalTTrackerHitDict();
extern void G__cpp_setup_memfuncTTrackerHitDict();
extern void G__cpp_setup_funcTTrackerHitDict();
extern void G__set_cpp_environmentTTrackerHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TTrackerHit.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTrackerHitDictLN_TClass;
extern G__linked_taginfo G__TTrackerHitDictLN_TBuffer;
extern G__linked_taginfo G__TTrackerHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TTrackerHitDictLN_TObject;
extern G__linked_taginfo G__TTrackerHitDictLN_string;
extern G__linked_taginfo G__TTrackerHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTrackerHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrackerHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTrackerHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrackerHitDictLN_TTrackerHit;
extern G__linked_taginfo G__TTrackerHitDictLN_TTrackerHitcLcLHitType;

/* STUB derived class for protected member access */
